export const LOGIN_ACTION = "LOGIN_ACTION";
export const GET_USER = "GET_USER";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const GET_FRIENDS = "GET_FRIENDS";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_IMAGE_SETS = "GET_IMAGE_SETS";
export const GET_PROJECT_IMAGE_SETS = "GET_PROJECT_IMAGE_SETS";
